MTRANS_P14T = [['Soil frost is possible there and in the southern low mountain ranges.',
  'La helada del suelo es posible allí y en las cadenas montañosas del sur.',
  'Le gel du sol est possible là-bas et dans les chaînes de montagnes basses du sud.'],
 ['Especially in the north and west, it clarifies in local ways in locally.',
  'Especialmente en el norte y oeste, se aclara de manera local en localmente.',
  "Surtout dans le nord et l'ouest, il clarifie de manière locale à Locally."],
 ['In Germany between twenty and sixty liters, there are enormous amounts of the square meter of the main focus of North Rhine Westphalia, but also the eastern Bavaria.',
  'En Alemania, entre veinte y sesenta litros, hay enormes cantidades del medidor cuadrado del enfoque principal de North Rhine Westfalia, pero también de Baviera Oriental.',
  "En Allemagne, entre vingt et soixante litres, il existe d'énormes quantités de mètre carré de l'objectif principal du Rhin nord-Westphalie, mais aussi de la Bavière orientale."],
 ['On Tuesday, the sun sometimes clouds during the day, sometimes violent showers and thunderstorms.',
  'El martes, el sol a veces nube durante el día, a veces duchas y tormentas eléctricas violentas.',
  'Mardi, le soleil obscurcit parfois pendant la journée, parfois des averses violentes et des orages.'],
 ['During the day, the sun shines a few denser cloud fields can appear, especially in the west and southwest, during the day.',
  'Durante el día, el sol brilla algunos campos de nubes más densos pueden aparecer, especialmente en el oeste y el suroeste, durante el día.',
  "Pendant la journée, le soleil brille quelques champs de nuages \u200b\u200bplus denses peuvent apparaître, en particulier à l'ouest et au sud-ouest, pendant la journée."],
 ['In the meantime, a deep run -down over the North Sea again steers rain clouds and cooler air.',
  'Mientras tanto, una carrera profunda sobre el Mar del Norte dibuja nubes de lluvia y aire más frío.',
  "Entre-temps, une course profonde sur la mer du Nord attire des nuages \u200b\u200bde pluie et de l'air plus frais."],
 ['The wind blows strong winds fresh in the north on the North Sea.',
  'El viento sopla fuertes vientos frescos en el norte en el Mar del Norte.',
  'Le vent souffle de forts vents frais au nord sur la mer du Nord.'],
 ['And from noon it starts to rain again on the North Sea in the afternoon on the Baltic Sea coast.',
  'Y desde el mediodía comienza a llover nuevamente en el Mar del Norte en la tarde en la costa del Mar Báltico.',
  "Et à partir de midi, il recommence à pleuvoir sur la mer du Nord dans l'après-midi sur la côte de la mer Baltique."],
 ['The wind blows weak to moderately from southwest to west.',
  'El viento sopla débil a moderadamente de suroeste a oeste.',
  "Le vent souffle faible à modérément du sud-ouest à l'ouest."],
 ['During the day it is sometimes friendly in the very south, otherwise dense clouds and some sun alternately.',
  'Durante el día, a veces es amigable en el mismo sur, de lo contrario nubes densas y algo de sol alternativamente.',
  'Pendant la journée, il est parfois amical dans le sud, sinon des nuages \u200b\u200bdenses et un peu de soleil alternativement.'],
 ['At night the rain pulls back to the Baltic Sea towards the south, it increasingly clarifies on the southern river valleys.',
  'Por la noche, la lluvia regresa al Mar Báltico hacia el sur, se aclara cada vez más en los valles del río sur.',
  'La nuit, la pluie recule vers la mer Baltique vers le sud, il clarifie de plus en plus sur les vallées du sud de la rivière.'],
 ['Many river levels have dropped even further since the weekend and a lot has to rain over a long time to replenish the levels.',
  'Muchos niveles de río han caído aún más desde el fin de semana y mucho tiene que llover durante mucho tiempo para reponer los niveles.',
  'De nombreux niveaux de rivière ont chuté encore plus loin depuis le week-end et beaucoup doivent pleuvoir sur une longue période pour reconstituer les niveaux.'],
 ['Have a nice evening and do it well.',
  'Que tengas una buena noche y hazlo bien.',
  'Passez une bonne soirée et faites-le bien.'],
 ['That is why the rain in the mountains is increasingly turning into snow.',
  'Es por eso que la lluvia en las montañas se está convirtiendo cada vez más en la nieve.',
  "C'est pourquoi la pluie dans les montagnes se transforme de plus en plus en neige."],
 ['And in the southeast in the afternoon a few showers.',
  'Y en el sureste por la tarde algunas duchas.',
  "Et dans le sud-est de l'après-midi, quelques averses."],
 ['The high above Finland is somewhat withdrawn, but the weather in eastern Germany continues.',
  'El alto por encima de Finlandia está algo retirado, pero el clima en el este de Alemania continúa.',
  "Le haut au-dessus de la Finlande est quelque peu retiré, mais la météo dans l'est de l'Allemagne se poursuit."],
 ['And now the weather forecast for tomorrow Wednesday the twentieth October.',
  'Y ahora el pronóstico del tiempo para mañana el miércoles del vigésimo octubre.',
  'Et maintenant les prévisions météorologiques pour demain mercredi le vingtième octobre.'],
 ['And now the weather forecast for tomorrow Tuesday.',
  'Y ahora el pronóstico del tiempo para mañana el martes.',
  'Et maintenant, les prévisions météorologiques pour demain mardi.'],
 ['From the lunchtime, the clouds from the northwest become even more densely light rain.',
  'Desde la hora del almuerzo, las nubes del noroeste se vuelven aún más densamente livianas.',
  "Depuis l'heure du déjeuner, les nuages \u200b\u200bdu nord-ouest deviennent encore plus densément légers."],
 ['From Friday a high will be noticeable and from the west it is slowly becoming friendlier again.',
  'A partir del viernes, se notará un máximo y desde el oeste se está volviendo más amigable nuevamente.',
  "Vendredi, un sommet sera perceptible et de l'ouest, il redevient lentement plus convivial."],
 ['The whole thing is accompanied by a partially lively south to west current.',
  'Todo está acompañado por una corriente parcialmente animada de Sur a Oeste.',
  "Le tout est accompagné d'un courant du sud à ouest partiellement animé."],
 ['To do this, a weaker winds from the southwest, sometimes moderate at the end of the coast.',
  'Para hacer esto, un viento más débil desde el suroeste, a veces moderado al final de la costa.',
  'Pour ce faire, un vents plus faibles du sud-ouest, parfois modéré au bout de la côte.'],
 ['Some rain only falls in the north.',
  'Alguna lluvia solo cae en el norte.',
  'Une certaine pluie ne tombe que dans le nord.'],
 ['And now the weather forecast for tomorrow Tuesday, eighth.',
  'Y ahora el pronóstico del tiempo para mañana martes, octavo.',
  'Et maintenant les prévisions météorologiques pour demain mardi, huitième.'],
 ['In the coming days it will mostly be very cloudy or foggy cloudy.',
  'En los próximos días estará en su mayoría muy nublado o nublado.',
  'Dans les prochains jours, il sera surtout très nuageux ou brumeux.'],
 ['The wind blows weak to moderately in the north and west, sometimes fresh with strong stormy gusts.',
  'El viento sopla débil a moderadamente en el norte y oeste, a veces fresco con fuertes ráfagas tormentosas.',
  "Le vent souffle faible à modérément au nord et à l'ouest, parfois frais avec de fortes rafales orageuses."],
 ['Otherwise it is not very strong tomorrow and then cloudy over the low mountain range.',
  'De lo contrario, no es muy fuerte mañana y luego nublado sobre la cordillera baja.',
  "Sinon, ce n'est pas très fort demain, puis nuageux sur la gamme de montagnes basse."],
 ['The influence also increases.',
  'La influencia también aumenta.',
  "L'influence augmente également."],
 ['The clouds in the west and southwest are a little more numerous.',
  'Las nubes en el oeste y el suroeste son un poco más numerosas.',
  "Les nuages \u200b\u200bà l'ouest et au sud-ouest sont un peu plus nombreux."],
 ['Only cloudy or clear in the north and there the sun has very good chances tomorrow.',
  'Solo nublado o claro en el norte y allí el sol tiene muy buenas oportunidades mañana.',
  'Seulement nuageux ou clair dans le nord et là, le soleil a de très bonnes chances demain.'],
 ['And now the weather forecast for tomorrow Saturday the twenty -three January.',
  'Y ahora el pronóstico del tiempo para mañana del sábado de veintisiete enero.',
  'Et maintenant les prévisions météorologiques pour demain samedi les vingt-trois janvier.'],
 ['On the edge of the Alps tonight seven in the northeast up to thirteen degrees.',
  'En el borde de los Alpes esta noche siete en el noreste de hasta trece grados.',
  "Sur le bord des Alpes ce soir, sept dans le nord-est jusqu'à treize degrés."]]

TRG_TRANS_P14T = ['dort sowie in den südlichen mittelgebirgen ist bodenfrost möglich.',
 'vor allem im norden und westen klart es gebietsweise auf örtlich bildet sich nebel.',
 'da fallen durchweg in deutschland zwischen zwanzig und sechzig liter auf den quadratmeter enorme mengen schwerpunkt vor allen dingen nordrhein westfalen aber auch das östliche bayern dabei.',
 'am dienstag mal sonne mal wolken im tagesverlauf zum teil heftige schauer und gewitter.',
 'am tag scheint verbreitet die sonne ein paar dichtere wolkenfelder können im laufe des tages vor allem im westen und südwesten auftauchen.',
 'währenddessen lenkt ein tiefausläufer über der nordsee wieder regenwolken und kühlere luft heran.',
 'der wind weht im norden frisch an der nordsee auch starker wind.',
 'und ab mittag fängt es an der nordsee auch wieder an zu regnen nachmittags an der ostseeküste.',
 'der wind weht schwach bis mäßig aus südwest bis west.',
 'am tag ist es ganz im süden teilweise noch länger freundlich sonst dichte wolken und etwas sonne im wechsel.',
 'in der nacht zieht sich der regen zur ostsee zurück richtung süden klart es zunehmend auf vor allem in den südlichen flusstälern bildet sich nebel.',
 'viele flusspegel sind seit dem wochenende noch weiter gesunken und da muss schon viel und über längere zeit regnen um die pegel wieder aufzufüllen.',
 'ihnen einen schönen abend und machen sie es gut.',
 'deshalb verwandelt sich der regen im bergland zunehmend in schnee.',
 'und im südosten am nachmittag auch wieder ein paar schauer.',
 'das hoch über finnland zieht sich zwar etwas zurück bestimmt aber weiter das wetter im osten deutschlands.',
 'und nun die wettervorhersage für morgen mittwoch den zwanzigsten oktober.',
 'und nun die wettervorhersage für morgen dienstag den vierzehnten juli.',
 'ab den mittagsstunden werden dann die wolken von nordwesten noch dichter leichter regen kommt auf.',
 'ab freitag macht sich dann ein hoch bemerkbar und von westen wird es langsam wieder freundlicher.',
 'das ganze wird von einer teilweise lebhaften süd bis west strömung begleitet.',
 'dazu weht ein schwacher in küstennähe teilweise mäßiger wind aus südwest.',
 'etwas regen fällt nur noch im norden.',
 'und nun die wettervorhersage für morgen dienstag den achten dezember.',
 'in den kommenden tagen ist es überwiegend stark bewölkt oder neblig trüb.',
 'der wind weht schwach bis mäßig im norden und westen teilweise frisch mit starken an der see stürmischen böen.',
 'auch sonst ist der wird nicht sehr stark morgen und dann wolkig über den mittelgebirgen.',
 'auch der hochdruckeinfluss nimmt zu.',
 'etwas zahlreicher sind die wolken im westen und südwesten.',
 'im norden nur locker bewölkt oder klar und dort hat die sonne morgen ganz gute chancen.',
 'und nun die wettervorhersage für morgen samstag den dreiundzwanzigsten januar.',
 'am alpenrand heute nacht sieben im nordosten noch bis dreizehn grad.']

MTRANS_H2S = [['no necesita usar un odómetro y realizar un seguimiento de cada milla que recorre.',
  "vous n'avez pas besoin d'utiliser un compteur kilométrique et de suivre chaque kilomètre parcouru.",
  'sie müssen keinen kilometerzähler verwenden und jede meile, die sie fahren, im auge behalten.'],
 ['quieres tomar tus hombros y llevarlos hacia tus orejas, vas a mantener dos o tres segundos y luego te vas a relajar.',
  'tu veux prendre tes épaules et les remonter vers tes oreilles, tu vas tenir deux ou trois secondes, puis tu vas te détendre.',
  'sie möchten ihre schultern nehmen und sie zu ihren ohren bringen, sie werden zwei oder drei sekunden halten und dann werden sie sich entspannen.'],
 ['entonces un bate menos tres sería un treinta dos veintinueve, o un treinta tres treinta, porque es tres onzas más liviano que la longitud.',
  'donc une chauve-souris moins trois donnerait un trente-deux vingt-neuf, ou un trente-trois trente, car elle est trois onces plus légère que la longueur.',
  'also würde ein minus drei fledermaus eine zweiunddreißigundundzwanzig oder einunddreißig dreiunddreißig, weil es drei unzen leichter ist als die länge.'],
 ['podría haber pequeños animales creciendo en tus peces.',
  'il pourrait y avoir de petits animaux qui poussent sur votre poisson.',
  'es könnte kleine tiere geben, die auf ihrem fisch wachsen.'],
 ['el primer paso de nuestro paisaje marino es sorpresa, sorpresa, no suministros.',
  'la première étape de notre paysage marin est la surprise, la surprise, pas le ravitaillement.',
  'der erste schritt unserer seelasen ist, überraschung, überraschung, nicht lieferungen.'],
 ['luego te damos papel de calco; un libro entero de papel de calco.',
  'puis nous vous donnons du papier calque ; tout un livre de papier calque.',
  'dann geben wir ihnen verfolgungspapier;ein ganzes buch mit verfolgungspapier.'],
 ['eso es todo, rebanar y cortar el pollo en cubitos.',
  "c'est tout pour trancher et couper votre poulet en dés.",
  'das ist es, ihr huhn zu schneiden und zu würfeln.'],
 ['obviamente, es un proceso por pasos.',
  'évidemment, c’est un processus par étapes.',
  'offensichtlich ist es ein schrittprozess.']]

TRG_TRANS_H2S = ["you don't need to use an odometer and keep track of every mile that you ride.",
 "you want to take your shoulders and bring them up towards your ears, you're going to hold two or three seconds, then you're going to relax.",
 "so a minus three bat would a thirty two twenty nine, or a thirty three thirty, because it's three ounces lighter than the length.",
 'there could be small animals growing on your fish.',
 'the first step of our seascape is, surprise, surprise, not supplies.',
 'then we give you tracing paper; a whole book of tracing paper.',
 'that is it on slicing and dicing your chicken.',
 'obviously, it is a step process.']